version: '3.8'

services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cursor-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - 6655:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
