spring:
  application.name: "scp-release-testapp"
  jpa:
    hibernate.ddl-auto: create
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: false
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:6543/reltest-db"
    username: "admin"
    password: "secret"
server:
  tomcat:
    relaxed-query-chars: "[,]"
