version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=reltest-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - 6543:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
