# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release_build:
        description: 'toggles an release-build, by default false'
        type: boolean
        default: false
        required: false
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_VERSION: '0-SNAPSHOT'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MAVEN_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
  GITHUBPKG_USERNAME: ${{ secrets.GITHUBPKG_USERNAME }}
  GITHUBPKG_PASSWORD: ${{ secrets.GITHUBPKG_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      maven_artifactId: ${{ steps.maven_artifactId.outputs.artifactId }}
      maven_groupId: ${{ steps.maven_groupId.outputs.groupId }}
      maven_version: ${{ steps.maven_version.outputs.version }}
      cache_key: ${{ steps.cache.outputs.cache_key }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
#      with:
#        dependency-graph: generate-and-submit

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      env:
        # Exclude all dependencies that originate solely in the 'buildSrc' or testapp project
        DEPENDENCY_GRAPH_EXCLUDE_PROJECTS: ':buildSrc|:cursorpaging-testapp'
        # Exclude dependencies that are only resolved in test classpaths
        DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS: '.*[Tt]est(Compile|Runtime)Classpath'
      with:
        build-scan-publish: true
        build-scan-terms-of-service-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-service-agree: "yes"